name: Build
on:
  push:
    branches:
      [master]
    paths:
      - 'src/**'
      - 'test/**'
      - 'CMakeLists.txt'
      - '.github/workflows/cmake.yaml'
jobs:
  build-project:
    name: Build Project
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: true

      - name: Configure CMake
        run: cmake -S . -B ./build

      - name: Build Project
        run: cmake --build build

      - name: Test Project
        run: ctest --test-dir build --output-on-failure


