name: Build
on:
  push:
jobs:
  build-project:
    name: Build Project
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Configure CMake
        run: cmake -S . -B cmake-build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=ninja

      - name: Build Project
        run: cmake --build cmake-build

      # - name: Test Project
      #   runs: ctest --test-dir build
  generate-docs:
    name: Generate Documentation
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Compile Documentation
        run: doxygen
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/doxygen
